#pragma once
// pango's generators, shared by the three members' build programs.
//
// Upstream has exactly two, which is why pango is a fork rather than a plain
// descriptor — the criterion in this index is GENERATORS, not line count:
//
//     configure_file          pango/pango-features.h.meson -> pango-features.h
//     configure_file          (no template at all)         -> config.h
//     gobject/glib-mkenums    pango_headers                -> pango-enum-types.{h,c}
//
// and this fork adds a fourth of its own, the C++23 module wrapper.
//
// ⚠️ EACH MEMBER GENERATES ITS OWN COPY into its own `include/`. That is not
// tidiness — it is the fix for a failure that is SILENT, measured in the glib
// fork: a member that lists a file another member's build program produces
// gets no error when the file is absent, just an object missing from the ninja
// file, surfacing much later as an undefined reference in a consumer.
//
// ⚠️ AND `include/.gitkeep` IS COMMITTED, because mcpp builds the compiler
// command line BEFORE running this program and silently drops an
// `include_dirs` entry naming a directory that does not exist yet.

#include "enums.h"

namespace {

// pango 1.56.1. Upstream splits meson.project_version() on '.'; the same three
// numbers land in pango-features.h and nowhere else.
constexpr int MAJOR = 1, MINOR = 56, MICRO = 1;

// ── meson configure_file -> pango/pango-features.h ──────────────────────────
//
// `#mesondefine X` becomes `#define X <value>`, and the one `@…@` in the file
// is the version string. Three substitutions total.
inline void gen_features()
{
    const fs::path in = g_up / "pango" / "pango-features.h.meson";
    std::string body = slurp(in);
    if (body.empty()) {
        note("pango-features.h.meson is empty or missing at %s\n", in.string().c_str());
        std::exit(1);
    }

    const std::pair<const char *, int> defs[] = {
        {"PANGO_VERSION_MAJOR", MAJOR},
        {"PANGO_VERSION_MINOR", MINOR},
        {"PANGO_VERSION_MICRO", MICRO},
    };
    for (const auto &[name, value] : defs) {
        const std::string k = std::string("#mesondefine ") + name;
        const std::size_t p = body.find(k);
        if (p == std::string::npos) {
            note("pango-features.h.meson no longer has `%s`; the generator and\n"
                 "the template have drifted apart.\n", k.c_str());
            std::exit(1);
        }
        body.replace(p, k.size(),
                     "#define " + std::string(name) + " " + std::to_string(value));
    }

    const std::string ver = std::to_string(MAJOR) + "." + std::to_string(MINOR)
                            + "." + std::to_string(MICRO);
    for (const char *name : {"PANGO_VERSION_MAJOR", "PANGO_VERSION_MINOR",
                             "PANGO_VERSION_MICRO"}) {
        const std::string k = std::string("@") + name + "@";
        for (std::size_t p = body.find(k); p != std::string::npos; p = body.find(k)) {
            const std::string v = std::strcmp(name, "PANGO_VERSION_MAJOR") == 0
                                      ? std::to_string(MAJOR)
                                  : std::strcmp(name, "PANGO_VERSION_MINOR") == 0
                                      ? std::to_string(MINOR)
                                      : std::to_string(MICRO);
            body.replace(p, k.size(), v);
        }
    }

    if (body.find('@') != std::string::npos || body.find("#mesondefine") != std::string::npos) {
        note("pango-features.h still has an unsubstituted placeholder:\n%s\n",
             body.c_str());
        std::exit(1);
    }

    std::error_code ec;
    fs::create_directories(g_inc / "pango", ec);
    std::ofstream(g_inc / "pango" / "pango-features.h")
        << "/* GENERATED by build.mcpp from upstream/pango/pango-features.h.meson. */\n"
        << body;
    mcpp::rerun_if_changed(in.string().c_str());
}

// ── gobject/glib-mkenums over pango's public headers ────────────────────────
//
// ⚠️ THE HEADER SET IS UPSTREAM'S `pango_headers`, DERIVED FROM pango.h RATHER
// THAN TRANSCRIBED. A hand-written list is one version bump from being wrong,
// and a dropped header is silent: the library simply lacks a GType that a
// consumer expects, and the failure lands in the consumer.
inline void gen_pango_enumtypes()
{
    const fs::path dir = g_up / "pango";

    std::vector<fs::path> headers;
    {
        std::ifstream h(dir / "pango.h");
        std::string l;
        while (std::getline(h, l)) {
            const std::size_t a = l.find("<pango/");
            if (a == std::string::npos) continue;
            const std::size_t b = l.find('>', a);
            if (b == std::string::npos) continue;
            const std::string n = l.substr(a + 7, b - a - 7);
            if (n.size() > 2 && n.compare(n.size() - 2, 2, ".h") == 0
                && fs::exists(dir / n))
                headers.push_back(dir / n);
        }
    }
    if (headers.size() < 20) {
        note("pango.h yielded only %zu headers; the enum scan would be silently\n"
             "incomplete and the library would be missing GTypes its own headers\n"
             "declare.\n", headers.size());
        std::exit(1);
    }

    std::vector<std::pair<std::string, std::vector<enum_def>>> per_file;
    std::size_t total = 0;
    for (const auto &h : headers) {
        auto e = scan_enums(h);
        mcpp::rerun_if_changed(h.string().c_str());
        if (e.empty()) continue;
        total += e.size();
        per_file.emplace_back(h.filename().string(), std::move(e));
    }
    if (total < 20) {
        note("only %zu enums found across pango's headers; upstream registers 28,\n"
             "and a short count means the scanner stopped understanding something.\n",
             total);
        std::exit(1);
    }

    std::error_code ec;
    fs::create_directories(g_inc / "pango", ec);
    write_enumtypes(dir / "pango-enum-types.h.template",
                    g_inc / "pango" / "pango-enum-types.h", per_file);
    write_enumtypes(dir / "pango-enum-types.c.template",
                    g_inc / "pango" / "pango-enum-types.c", per_file);
    note("pango-enum-types: %zu enums across %zu headers\n", total, per_file.size());
}

// ── meson configure_file -> config.h ────────────────────────────────────────
//
// ⚠️ THERE IS NO TEMPLATE. `configure_file(output: 'config.h', configuration:
// pango_conf)` with no `input:` makes meson emit a `#define` per key it was
// given, so there is nothing in the tree to substitute into — the file has to
// be WRITTEN, and every value in it is a decision this package makes.
//
// The two that are not decisions but arithmetic, straight from meson.build:26:
//
//     PANGO_BINARY_AGE    = minor * 100 + micro
//     PANGO_INTERFACE_AGE = minor is odd ? 0 : micro
//
// pango_utils.c reads BINARY_AGE in pango_version_check(), so getting it wrong
// makes a correct version comparison answer wrongly at RUN TIME rather than
// failing to build.
//
// ⚠️ EVERY `HAVE_*` BELOW IS ABSENT RATHER THAN 0, and that is not cosmetic:
// pango tests them with `#ifdef`, so `#define HAVE_LIBTHAI 0` would mean YES
// and pull in calls to a library that is not linked. The glib fork shipped
// exactly that mistake nine times over before it was caught.
//
//     HAVE_LIBTHAI    Thai line breaking — libthai is not in this index
//     HAVE_SYSPROF    tracing — sysprof-capture is not in this index
//     HAVE_CORE_TEXT  macOS
//     HAVE_CAIRO_*    set by the pangocairo member, not here
// `extra` is what THIS member adds: HAVE_FREETYPE for pangoft2, HAVE_CAIRO and
// HAVE_CAIRO_FREETYPE for pangocairo. Upstream sets them from whether the
// dependency was found; here the member that declares the dependency is the
// member that sets the macro, which is the same statement without the search.
inline void gen_config(const std::vector<std::string> &extra = {})
{
    std::error_code ec;
    fs::create_directories(g_inc, ec);
    std::ofstream o(g_inc / "config.h");
    o << "/* GENERATED by build.mcpp. Upstream produces this with a\n"
         " * configure_file that has NO input template, so this is written\n"
         " * rather than substituted. See mcpp/common/prelude.h. */\n"
         "#pragma once\n\n";
    o << "#define PANGO_VERSION_MAJOR " << MAJOR << "\n";
    o << "#define PANGO_VERSION_MINOR " << MINOR << "\n";
    o << "#define PANGO_VERSION_MICRO " << MICRO << "\n\n";
    o << "/* meson.build:31 - minor * 100 + micro. pango_version_check() reads\n"
         " * this, so a wrong value is a wrong ANSWER rather than a build error. */\n";
    o << "#define PANGO_BINARY_AGE " << (MINOR * 100 + MICRO) << "\n";
    o << "/* meson.build:30 - 0 when the minor version is odd (a devel series),\n"
         " * the micro version otherwise. 1.56 is stable. */\n";
    o << "#define PANGO_INTERFACE_AGE " << (MINOR % 2 ? 0 : MICRO) << "\n\n";
    o << "/* Upstream sets this from the compiler's visibility support; this is\n"
         " * its non-Windows branch, meson.build:170. */\n"
         "#define _PANGO_EXTERN __attribute__((visibility(\"default\"))) extern\n\n";
    o << "/* C99 variadic macros. Both compilers this package is built with have\n"
         " * them, and pango prefers the ISO form when both are offered. */\n"
         "#define HAVE_ISO_VARARGS 1\n\n";

    // ⚠️ THE PER-MEMBER HALF, AND LEAVING IT OUT DEGRADES SILENTLY. This loop
    // was lost once in an edit, and the result was not a build failure: with
    // HAVE_CAIRO_FREETYPE undefined, pangocairo-fontmap.c registers NO
    // backends, `pango_cairo_font_map_get_default()` returns nothing usable,
    // and the program dies at run time with
    //
    //     Pango-CRITICAL: Unknown $PANGOCAIRO_BACKEND value.
    //       Available backends are:            <- an empty list
    //
    // followed by a segfault. Everything compiled and linked.
    o << "/* Set by THIS member, because it is the member that declares the\n"
         " * dependency the macro is about. */\n";
    for (const auto &e : extra) {
        o << "#define " << e << " 1\n";
    }
    if (extra.empty()) {
        o << "/* (none — this member has no backend of its own) */\n";
    }

    mcpp::rerun_if_changed("../common/prelude.h");
}


// ⚠️ pango INCLUDES ITS GENERATED HEADERS BOTH WAYS, and both have to work.
// Measured across upstream/pango:
//
//     "pango-features.h"    1     <pango/pango-features.h>    2
//     "pango-enum-types.h"  2     <pango/pango-enum-types.h>  2
//
// The real file lives under `pango/` so the angle-bracket form resolves
// through `include/`; a one-line forwarder at the top level answers the bare
// spelling. Forwarding rather than writing twice keeps one source of truth,
// and the nested directory needs no `include_dirs` entry of its own — which
// matters, because an entry naming a directory that does not exist yet is
// silently dropped.
inline void gen_flat_forwarders()
{
    for (const char *n : {"pango-features.h", "pango-enum-types.h"}) {
        std::ofstream(g_inc / n)
            << "/* GENERATED by build.mcpp.\n"
               " *\n"
               " * pango includes this both as \"" << n << "\" and as\n"
               " * <pango/" << n << ">. The real file is the nested one;\n"
               " * this answers the bare spelling. */\n"
            << "#include <pango/" << n << ">\n";
    }
}

// The setup every member repeats: locate the tree and write the two shared
// outputs into THIS member's include/.
inline void pango_common_setup(const std::vector<std::string> &config_extra = {})
{
    g_root = fs::path(mcpp::manifest_dir());
    g_up   = (g_root / ".." / ".." / "upstream").lexically_normal();
    g_inc  = (g_root / "include").lexically_normal();

    std::error_code ec;
    // Wiped so a header that stopped being generated stops shadowing too. The
    // DIRECTORY survives with its .gitkeep — see the note at the top.
    fs::remove_all(g_inc / "pango", ec);
    fs::remove(g_inc / "config.h", ec);
    fs::create_directories(g_inc, ec);

    gen_config(config_extra);
    gen_features();
    gen_pango_enumtypes();
    gen_flat_forwarders();
}

} // namespace
